apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-controller-sa
  namespace: default
#automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-controller-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/status", "deployments"]
  verbs: ["update", "patch", "get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-controller-rb
subjects:
- kind: ServiceAccount
  name: pod-controller-sa
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: pod-controller-role
  apiGroup: rbac.authorization.k8s.io