apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-numbers
spec:
  selector:
    matchLabels:
      app: prime-numbers
  replicas: 1
  template:
    metadata:
      labels:
        app: prime-numbers
        autoscaling: kosmos
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - prime-numbers
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: pod-controller-sa
      containers:
        - name: prime-numbers
          image: systemautoscaler/prime-numbers:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 250m
        - name: http-metrics
          image: systemautoscaler/http-metrics:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: ADDRESS
              value: "localhost"
            - name: PORT
              value: "8080"
            - name: WINDOW_SIZE
              value: "30s"
            - name: WINDOW_GRANULARITY
              value: "1ms"
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 250m
        - name: proxy-vertical-scaling
          image: quintero98/kversca20:0.1
          imagePullPolicy: Always
          env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_NS_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_DP_NAME
            value: prime-numbers # Must be changed manually
          - name: MY_APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['app']
          - name: CONTAINER_TO_FORWARD
            value: http-metrics
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 150Mi
              cpu: 250m
            limits:
              memory: 150Mi
              cpu: 250m