apiVersion: v1
kind: Service
metadata:
  name: prime-numbers
  labels:
    app: prime-numbers
spec:
  selector:
    app: prime-numbers
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31512
    protocol: TCP
