apiVersion: apps/v1
kind: Deployment
metadata:
  name: sebs-compression
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sebs-compression
  template:
    metadata:
      labels:
        app: sebs-compression
        autoscaling: Kosmos
        logger: "on"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - sebs-compression
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: pod-controller-sa
      containers:
        - name: sebs-compression
          image: quintero98/sebs:v0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resizePolicy:
            - resourceName: cpu
              restartPolicy: NotRequired
            - resourceName: memory
              restartPolicy: NotRequired
          resources:
            requests:
              memory: 1Gi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 250m
        - name: http-metrics
          image: systemautoscaler/http-metrics:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: ADDRESS
              value: "localhost"
            - name: PORT
              value: "8080"
            - name: WINDOW_SIZE
              value: "30s"
            - name: WINDOW_GRANULARITY
              value: "1ms"
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 250m
        - name: metrics-logger
          image: quintero98/metrics-logger:v0.1
          imagePullPolicy: Always
          env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_NS_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_DP_NAME
            value: sebs-compression # Must be changed manually
          - name: MY_APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['app']
          resources:
            requests:
              memory: 150Mi
              cpu: 250m
            limits:
              memory: 150Mi
              cpu: 250m
          volumeMounts:
          - name: persistent-storage
            mountPath: /data 
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: mypvc
---
kind: Service
apiVersion: v1
metadata:
  name: sebs-compression
  labels:
    app: sebs-compression
spec:
  selector:
    app: sebs-compression
  type: NodePort
  ports:
    - port: 8000
      targetPort: 80
      nodePort: 31080
      protocol: TCP