apiVersion: systemautoscaler.polimi.it/v1beta1
kind: ServiceLevelAgreement
metadata:
  name: sebs-compression
spec:
  metric:
    responseTime: 100m
  defaultResources:
    memory: 1Gi
    cpu: 250m
  minResources:
    memory: 500Mi
    cpu: 100m
  maxResources:
    memory: 4Gi
    cpu: 2000m
  service:
    container: sebs-compression
    selector:
      matchLabels:
        app: sebs-compression
---
apiVersion: systemautoscaler.polimi.it/v1beta1
kind: ServiceLevelAgreement
metadata:
  name: sebs-dynamic-html
spec:
  metric:
    responseTime: 100m
  defaultResources:
    memory: 2Gi
    cpu: 250m
  minResources:
    memory: 500Mi
    cpu: 100m
  maxResources:
    memory: 4Gi
    cpu: 2000m
  service:
    container: sebs-dynamic-html
    selector:
      matchLabels:
        app: sebs-dynamic-html
---
apiVersion: systemautoscaler.polimi.it/v1beta1
kind: ServiceLevelAgreement
metadata:
  name: sebs-graph-mst
spec:
  metric:
    responseTime: 100m
  defaultResources:
    memory: 1Gi
    cpu: 250m
  minResources:
    memory: 500Mi
    cpu: 100m
  maxResources:
    memory: 4Gi
    cpu: 2000m
  service:
    container: sebs-graph-mst
    selector:
      matchLabels:
        app: sebs-graph-mst
---
apiVersion: systemautoscaler.polimi.it/v1beta1
kind: ServiceLevelAgreement
metadata:
  name: sebs-thumbnailer
spec:
  metric:
    responseTime: 100m
  defaultResources:
    memory: 4Gi
    cpu: 250m
  minResources:
    memory: 1Gi
    cpu: 100m
  maxResources:
    memory: 6Gi
    cpu: 2000m
  service:
    container: sebs-thumbnailer
    selector:
      matchLabels:
        app: sebs-thumbnailer