apiVersion: apps/v1
kind: Deployment
metadata:
  name: spy
spec:
  selector:
    matchLabels:
      app: spy
  replicas: 6 # number of total nodes (control-plane and worker)
  template:
    metadata:
      labels:
        app: spy

    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - spy
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: pod-controller-sa
      containers:
        - name: spy
          image: systemautoscaler/prime-numbers:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resizePolicy:
            - resourceName: cpu
              restartPolicy: NotRequired
            - resourceName: memory
              restartPolicy: NotRequired
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 250m
          volumeMounts:
          - name: persistent-storage
            mountPath: /data 
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: mypvc